In [1]:
import pandas as pd
import numpy as np
from tqdm.auto import tqdm, trange

In [2]:
data = pd.read_csv('dump.csv')

In [3]:
data.shape

(83707, 5)

In [4]:
data.head(5)

,Название,Артикул,Категория,Цена без карты,Цена с картой
0,Проходка BORGE Кровельная D6-50мм прямая №1,17162301,"Главная,Каталог,Строительные материалы,Кровля,...",329.33 ₽,312.86 ₽
1,Аэратор ТЕХНОНИКОЛЬ КТВ,17575401,"Главная,Каталог,Строительные материалы,Кровля,...",1 529.00 ₽,1 452.55 ₽
2,Аэратор ТЕХНОНИКОЛЬ Pilot скатный,17575301,"Главная,Каталог,Строительные материалы,Кровля,...",3 008.00 ₽,2 857.60 ₽
3,Проходной элемент ТЕХНОНИКОЛЬ Shinglas,17575701,"Главная,Каталог,Строительные материалы,Кровля,...",1 172.00 ₽,1 113.40 ₽
4,Вентиль ТЕХНОНИКОЛЬ Skat кровельный,17575501,"Главная,Каталог,Строительные материалы,Кровля,...",2 396.00 ₽,2 276.20 ₽

In [5]:
print(data['Категория'].unique(), len(data['Категория'].unique()))

['Главная,Каталог,Строительные материалы,Кровля,Вентиляция для кровли'
 'Главная,Каталог,Строительные материалы,Кровля,Волнистый лист (ондулин)'
 'Главная,Каталог,Строительные материалы,Кровля,Кровельные мастики'
 'Главная,Каталог,Строительные материалы,Кровля,Кровельные ограждения, снегодержатели'
 'Главная,Каталог,Строительные материалы,Кровля,Металлочерепица'
 'Главная,Каталог,Строительные материалы,Кровля,Мягкая черепица'
 'Главная,Каталог,Строительные материалы,Кровля,Профнастил'
 'Главная,Каталог,Строительные материалы,Кровля,Рулонная кровля'
 'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Затирки'
 'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Клеи'
 'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Ровнители для пола'
 'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Специальные смеси'
 'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Шпаклевки'
 'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Штукатурки'
 'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Гипсокартон'
 'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Комплектующие для гипсокартона'
 'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Профиль для гипсокартона'
 'Главная,Каталог,Строительные материалы,Материалы для кладки,Кирпич'
 'Главная,Каталог,Строительные материалы,Материалы для кладки,Пазогребневые блоки и плиты'
 'Главная,Каталог,Строительные материалы,Материалы для кладки,Пенобетонные блоки'
 'Главная,Каталог,Строительные материалы,Металлическая арматура'
 'Главная,Каталог,Строительные материалы,Столярные изделия,Вагонка,  блок-хаус'
 'Главная,Каталог,Строительные материалы,Столярные изделия,Двери жалюзийные'
 'Главная,Каталог,Строительные материалы,Столярные изделия,Деревянные окна'
 'Главная,Каталог,Строительные материалы,Столярные изделия,Доска для пола и комплектующие'
 'Главная,Каталог,Строительные материалы,Столярные изделия,Доска обрезная'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Специальный крепеж'
 'Главная,Каталог,Строительные материалы,Столярные изделия,Лестничные группы'
 'Главная,Каталог,Строительные материалы,Столярные изделия,Погонажные изделия'
 'Главная,Каталог,Строительные материалы,Листовые материалы,OSB'
 'Главная,Каталог,Строительные материалы,Листовые материалы,ДВП'
 'Главная,Каталог,Строительные материалы,Листовые материалы,ДСП'
 'Главная,Каталог,Строительные материалы,Листовые материалы,Металлические листы'
 'Главная,Каталог,Строительные материалы,Листовые материалы,Пластик'
 'Главная,Каталог,Строительные материалы,Листовые материалы,Фанера'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Гидроизоляционные материалы'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Лента изоляционная и соединительная'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Материалы для осушения и защиты от солей кладок старых зданий'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Минеральная теплоизоляция'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенопласт'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенополистирол'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Плёнки и утеплители'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Поролон и войлок'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Рулонные и битумные кровельные материалы'
 'Главная,Каталог,Строительные материалы,Материалы для изоляции,Уплотнители'
 'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Бордюры тротуарные и водостоки'
 'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Водостоки и дренаж'
 'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Кольца и колодцы'
 'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Плитка тротуарная и формы'
 'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Решетки водоприемные'
 'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Трубы канализационные'
 'Главная,Каталог,Строительные материалы,Материалы для фасадов,Калитки и ограждения'
 'Главная,Каталог,Строительные материалы,Материалы для фасадов,Кованные изделия'
 'Главная,Каталог,Строительные материалы,Материалы для фасадов,Листовая кровля'
 'Главная,Каталог,Строительные материалы,Материалы для фасадов,Сайдинг'
 'Главная,Каталог,Строительные материалы,Материалы для фасадов,Система водоотвода'
 'Главная,Каталог,Двери, окна, замки,Двери межкомнатные'
 'Главная,Каталог,Двери, окна, замки,Двери стальные'
 'Главная,Каталог,Двери, окна, замки,Дверные коробки, наличники и доборы'
 'Главная,Каталог,Двери, окна, замки,Дверные доводчики'
 'Главная,Каталог,Двери, окна, замки,Ручки дверные'
 'Главная,Каталог,Двери, окна, замки,Стопоры дверные'
 'Главная,Каталог,Двери, окна, замки,Петли'
 'Главная,Каталог,Двери, окна, замки,Капители и арки'
 'Главная,Каталог,Двери, окна, замки,Аксессуары для дверей'
 'Главная,Каталог,Двери, окна, замки,Оконная группа,Монтаж окон'
 'Главная,Каталог,Двери, окна, замки,Оконная группа,Москитные сетки и плёнки для окон'
 'Главная,Каталог,Двери, окна, замки,Оконная группа,Оконная фурнитура'
 'Главная,Каталог,Двери, окна, замки,Оконная группа,Откосы'
 'Главная,Каталог,Двери, окна, замки,Оконная группа,Отливы'
 'Главная,Каталог,Двери, окна, замки,Оконная группа,Пластиковые окна'
 'Главная,Каталог,Двери, окна, замки,Оконная группа,Подоконники'
 'Главная,Каталог,Двери, окна, замки,Оконная группа,Уплотнители'
 'Главная,Каталог,Двери, окна, замки,Замки и комплектующие'
 'Главная,Каталог,Двери, окна, замки,Крючки, шпингалеты и задвижки'
 'Главная,Каталог,Двери, окна, замки,Заготовки ключей и брелоки'
 'Главная,Каталог,Двери, окна, замки,Дверцы для кошек'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Анкера'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Верёвки, шнуры'
 'Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Комплектующие для транспортировки грузов'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Гвозди'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Дюбели'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Заклёпки'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Крепления для зеркал'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Метрический крепеж, шайбы'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Навесные замки и комплектующие'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Пластины крепежные'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Саморезы'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Такелажный крепёж'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Уголки'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Хомуты, скобы'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Цепи и тросы'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы'
 'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы кровельные'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Аккумуляторные дрели и шуруповерты'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Дрели'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Зарядные и пусковые устройства'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Лобзики'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Многофункциональный инструмент'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Перфораторы'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Пилы дисковые, ленточный, сабельные'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Рубанки и рейсмусы'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Углошлифмашины и полировальные машины'
 'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Шлифмашины и граверы'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Биты, насадки'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Буры'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Диски, круги'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Зубила, штробники'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Кордщётки'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Коронки'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Круги полировочные и шлифовальные'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Листы, сетки шлифовальные'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Масла и смазки для инструмента'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Пилки, полотна, ножи'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для бензопил'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для компрессоров'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для минимоек'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для пылесосов'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для сварки'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для степлеров'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Свёрла, патроны'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Фрезы'
 'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Шарошки'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Гвоздодёры, ломы'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Заклёпочники'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Зубила, кернеры, штробники'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Ключи разводные'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Ключи рожковые, накидные, комбинированные'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Наборы инструментов'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Крепления для инструментов'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Напильники, надфили, точила'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Ножи, ножницы, лезвия, стеклорезы'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Ножовки, стусло'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Отвёртки'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Резьбонарезной инструмент'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Рубанки'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Сантехнический инструмент'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Скобозабивной инструмент'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Стамески'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Станки и комплектующие'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Тиски, струбцины, зажимы'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Трещотки, головки'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Ударный инструмент'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Шарнирно-губцевый инструмент'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Щётки'
 'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Ящики, органайзеры и контейнеры для инструментов'
 'Главная,Каталог,Инструменты и крепёж,Измерительно-разметочный инструмент,Комплектующие для измерительных инструментов'
 'Главная,Каталог,Инструменты и крепёж,Измерительно-разметочный инструмент,Лазерные измерители'
 'Главная,Каталог,Инструменты и крепёж,Измерительно-разметочный инструмент,Линейки, рулетки'
 'Главная,Каталог,Инструменты и крепёж,Измерительно-разметочный инструмент,Металлоискатели, искатели проводки'
 'Главная,Каталог,Инструменты и крепёж,Измерительно-разметочный инструмент,Оптические измерители'
 'Главная,Каталог,Инструменты и крепёж,Измерительно-разметочный инструмент,Пирометры'
 'Главная,Каталог,Инструменты и крепёж,Измерительно-разметочный инструмент,Разметочный инструмент'
 'Главная,Каталог,Обои,Инструмент для поклейки обоев'
 'Главная,Каталог,Инструменты и крепёж,Измерительно-разметочный инструмент,Уровни и угольники'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Ёмкости для красок и растворов'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Валики, ролики малярные'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Гладилки'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Гребенка'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Кисти'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Мастерки, кельмы'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Миксеры строительные'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Пистолеты для герметика и монтажной пены'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Плиткорезы и запчасти к ним'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Правило'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Стеклорезы'
 'Главная,Каталог,Инструменты и крепёж,Отделочный инструмент,Тёрки, шпатели'
 'Главная,Каталог,Инструменты и крепёж,Компрессоры, пневмоинструмент,Компрессоры'
 'Главная,Каталог,Инструменты и крепёж,Компрессоры, пневмоинструмент,Краскопульты пневматические'
 'Главная,Каталог,Инструменты и крепёж,Компрессоры, пневмоинструмент,Краскораспылители'
 'Главная,Каталог,Инструменты и крепёж,Компрессоры, пневмоинструмент,Набор пневмоинструментов'
 'Главная,Каталог,Инструменты и крепёж,Компрессоры, пневмоинструмент,Пистолет пневматический'
 'Главная,Каталог,Инструменты и крепёж,Компрессоры, пневмоинструмент,Степлеры и нейлеры'
 'Главная,Каталог,Инструменты и крепёж,Компрессоры, пневмоинструмент,Шланги'
 'Главная,Каталог,Инструменты и крепёж,Сварочное оборудование,Комплектующие для сварочных аппаратов'
 'Главная,Каталог,Инструменты и крепёж,Сварочное оборудование,Паяльники для полипропиленовых труб'
 'Главная,Каталог,Инструменты и крепёж,Сварочное оборудование,Сварочные аппараты'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Бетономешалки'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Виброплиты'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Газовые резаки'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Горелки'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Клеевые пистолеты'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Краскопульты'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Лампы паяльные'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Леса'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Моечные машины, пылесосы'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Паяльники'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Стеллажи'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Стремянки и верстаки'
 'Главная,Каталог,Инструменты и крепёж,Специальный инструмент и оборудование,Фены технические'
 'Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Домкраты'
 'Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Колеса, колесные опоры'
 'Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Лебёдки, тали'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Защита лица'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Защитные крема'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Каски'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Комбинезоны жилеты и халаты'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Наколенники'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Наушники и беруши'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Перчатки, рукавицы'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Респираторы и маски'
 'Главная,Каталог,Инструменты и крепёж,Средства защиты труда,Страховочные пояса'
 'Главная,Каталог,Напольные покрытия,Ламинат'
 'Главная,Каталог,Напольные покрытия,Линолеум'
 'Главная,Каталог,Напольные покрытия,Ковролин'
 'Главная,Каталог,Напольные покрытия,Дорожки, ковры'
 'Главная,Каталог,Напольные покрытия,Паркет'
 'Главная,Каталог,Потолочные и стеновые покрытия,Декоративный натуральный материал,Пробковые покрытия'
 'Главная,Каталог,Напольные покрытия,Пробковые покрытия'
 'Главная,Каталог,Напольные покрытия,Плитка ПВХ'
 'Главная,Каталог,Напольные покрытия,Подложки для напольных покрытий'
 'Главная,Каталог,Напольные покрытия,Плинтуса, уголки'
 'Главная,Каталог,Напольные покрытия,Пороги'
 'Главная,Каталог,Напольные покрытия,Грязеулавливатели'
 'Главная,Каталог,Напольные покрытия,Аксессуары для напольных покрытий'
 'Главная,Каталог,Напольные покрытия,Сварочные шнуры'
 'Главная,Каталог,Напольные покрытия,Клей для напольных покрытий'
 'Главная,Каталог,Напольные покрытия,Противоскользящие материалы'
 'Главная,Каталог,Напольные покрытия,Материалы для реставрации напольных покрытий'
 'Главная,Каталог,Напольные покрытия,Инструменты для монтажа'
 'Главная,Каталог,Керамическая плитка,Напольная плитка'
 'Главная,Каталог,Керамическая плитка,Настенная плитка'
 'Главная,Каталог,Керамическая плитка,Керамогранит'
 'Главная,Каталог,Керамическая плитка,Ступени'
 'Главная,Каталог,Керамическая плитка,Клинкерная плитка, клинкерные ступени'
 'Главная,Каталог,Керамическая плитка,Панно'
 'Главная,Каталог,Керамическая плитка,Бордюры и плинтуса'
 'Главная,Каталог,Керамическая плитка,Декоры'
 'Главная,Каталог,Керамическая плитка,Аксессуары для керамической плитки'
 'Главная,Каталог,Керамическая плитка,Крестики, клинья для плитки'
 'Главная,Каталог,Керамическая плитка,Декоративный камень'
 'Главная,Каталог,Керамическая плитка,Мозаика'
 'Главная,Каталог,Керамическая плитка,Стеклоблоки'
 'Главная,Каталог,Обои,Обои 0,53' 'Главная,Каталог,Обои,Обои 0,7'
 'Главная,Каталог,Обои,Обои  1,06'
 'Главная,Каталог,Обои,Обои под покраску'
 'Главная,Каталог,Обои,Жидкие обои' 'Главная,Каталог,Обои,Фотообои'
 'Главная,Каталог,Обои,Подложка под обои'
 'Главная,Каталог,Обои,Клей для обоев'
 'Главная,Каталог,Обои,Грунтовка и средства для снятия обоев'
 'Главная,Каталог,Обои,Бордюры и панно'
 'Главная,Каталог,Обои,Декоративные наклейки'
 'Главная,Каталог,Обои,Углы и профили'
 'Главная,Каталог,Потолочные и стеновые покрытия,Потолочные покрытия,Подвесные потолки'
 'Главная,Каталог,Потолочные и стеновые покрытия,Декоративный потолок,Багет'
 'Главная,Каталог,Потолочные и стеновые покрытия,Декоративный потолок,Балки потолочные'
 'Главная,Каталог,Потолочные и стеновые покрытия,Декоративный потолок,Галтели'
 'Главная,Каталог,Потолочные и стеновые покрытия,Декоративный потолок,Декоративные панели и вставки'
 'Главная,Каталог,Потолочные и стеновые покрытия,Декоративный потолок,Карнизы'
 'Главная,Каталог,Потолочные и стеновые покрытия,Декоративный потолок,Кессоны'
 'Главная,Каталог,Потолочные и стеновые покрытия,Декоративный потолок,Клей для потолочной плитки'

In [6]:
print(data['Название'].unique(), len(data['Название'].unique()))

['Проходка BORGE Кровельная D6-50мм прямая №1' 'Аэратор ТЕХНОНИКОЛЬ КТВ'
 'Аэратор ТЕХНОНИКОЛЬ Pilot скатный' ...
 'Решётка заборная FULEREN 15х15 0,5х5мх'
 'Решётка заборная FULEREN 15х15 0,5х10м'
 'Сетка сварная FULEREN Оцинкованная 50х100 1,8х15м'] 82921

# Выборка данных

In [7]:
topics = [
          'Главная,Каталог,Строительные материалы,Кровля,Вентиляция для кровли',
          'Главная,Каталог,Строительные материалы,Кровля,Волнистый лист (ондулин)',
          'Главная,Каталог,Строительные материалы,Кровля,Кровельные мастики',
          'Главная,Каталог,Строительные материалы,Кровля,Кровельные ограждения, снегодержатели',
          'Главная,Каталог,Строительные материалы,Кровля,Металлочерепица',
          'Главная,Каталог,Строительные материалы,Кровля,Мягкая черепица',
          'Главная,Каталог,Строительные материалы,Кровля,Профнастил',
          'Главная,Каталог,Строительные материалы,Кровля,Рулонная кровля',
          'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Затирки',
          'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Клеи',
          'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Ровнители для пола',
          'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Специальные смеси',
          'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Шпаклевки',
          'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Штукатурки',
          'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Гипсокартон',
          'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Комплектующие для гипсокартона',
          'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Профиль для гипсокартона',
          'Главная,Каталог,Строительные материалы,Материалы для кладки,Кирпич',
          'Главная,Каталог,Строительные материалы,Материалы для кладки,Пазогребневые блоки и плиты',
          'Главная,Каталог,Строительные материалы,Материалы для кладки,Пенобетонные блоки',
          'Главная,Каталог,Строительные материалы,Металлическая арматура',
          'Главная,Каталог,Строительные материалы,Столярные изделия,Вагонка,  блок-хаус',
          'Главная,Каталог,Строительные материалы,Столярные изделия,Двери жалюзийные',
          'Главная,Каталог,Строительные материалы,Столярные изделия,Деревянные окна',
          'Главная,Каталог,Строительные материалы,Столярные изделия,Доска для пола и комплектующие',
          'Главная,Каталог,Строительные материалы,Столярные изделия,Доска обрезная',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Специальный крепеж',
          'Главная,Каталог,Строительные материалы,Столярные изделия,Лестничные группы',
          'Главная,Каталог,Строительные материалы,Столярные изделия,Погонажные изделия',
          'Главная,Каталог,Строительные материалы,Листовые материалы,OSB',
          'Главная,Каталог,Строительные материалы,Листовые материалы,ДВП',
          'Главная,Каталог,Строительные материалы,Листовые материалы,ДСП',
          'Главная,Каталог,Строительные материалы,Листовые материалы,Металлические листы',
          'Главная,Каталог,Строительные материалы,Листовые материалы,Пластик',
          'Главная,Каталог,Строительные материалы,Листовые материалы,Фанера',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Гидроизоляционные материалы',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Лента изоляционная и соединительная',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Материалы для осушения и защиты от солей кладок старых зданий',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Минеральная теплоизоляция',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенопласт',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенополистирол',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Плёнки и утеплители',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Поролон и войлок',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Рулонные и битумные кровельные материалы',
          'Главная,Каталог,Строительные материалы,Материалы для изоляции,Уплотнители',
          'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Бордюры тротуарные и водостоки',
          'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Водостоки и дренаж',
          'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Кольца и колодцы',
          'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Плитка тротуарная и формы',
          'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Решетки водоприемные',
          'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Трубы канализационные',
          'Главная,Каталог,Строительные материалы,Материалы для фасадов,Калитки и ограждения',
          'Главная,Каталог,Строительные материалы,Материалы для фасадов,Кованные изделия',
          'Главная,Каталог,Строительные материалы,Материалы для фасадов,Листовая кровля',
          'Главная,Каталог,Строительные материалы,Материалы для фасадов,Сайдинг',
          'Главная,Каталог,Строительные материалы,Материалы для фасадов,Система водоотвода',
          'Главная,Каталог,Двери, окна, замки,Двери межкомнатные',
          'Главная,Каталог,Двери, окна, замки,Двери стальные',
          'Главная,Каталог,Двери, окна, замки,Дверные коробки, наличники и доборы',
          'Главная,Каталог,Двери, окна, замки,Дверные доводчики',
          'Главная,Каталог,Двери, окна, замки,Ручки дверные',
          'Главная,Каталог,Двери, окна, замки,Стопоры дверные',
          'Главная,Каталог,Двери, окна, замки,Петли',
          'Главная,Каталог,Двери, окна, замки,Капители и арки',
          'Главная,Каталог,Двери, окна, замки,Аксессуары для дверей',
          'Главная,Каталог,Двери, окна, замки,Оконная группа,Монтаж окон',
          'Главная,Каталог,Двери, окна, замки,Оконная группа,Москитные сетки и плёнки для окон',
          'Главная,Каталог,Двери, окна, замки,Оконная группа,Оконная фурнитура',
          'Главная,Каталог,Двери, окна, замки,Оконная группа,Откосы',
          'Главная,Каталог,Двери, окна, замки,Оконная группа,Отливы',
          'Главная,Каталог,Двери, окна, замки,Оконная группа,Пластиковые окна',
          'Главная,Каталог,Двери, окна, замки,Оконная группа,Подоконники',
          'Главная,Каталог,Двери, окна, замки,Оконная группа,Уплотнители',
          'Главная,Каталог,Двери, окна, замки,Замки и комплектующие',
          'Главная,Каталог,Двери, окна, замки,Крючки, шпингалеты и задвижки',
          'Главная,Каталог,Двери, окна, замки,Заготовки ключей и брелоки',
          'Главная,Каталог,Двери, окна, замки,Дверцы для кошек',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Анкера',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Верёвки, шнуры',
          'Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Комплектующие для транспортировки грузов',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Гвозди',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Дюбели',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Заклёпки',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Крепления для зеркал',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Метрический крепеж, шайбы',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Навесные замки и комплектующие',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Пластины крепежные',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Саморезы',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Такелажный крепёж',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Уголки',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Хомуты, скобы',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Цепи и тросы',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы',
          'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы кровельные',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Аккумуляторные дрели и шуруповерты',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Дрели',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Зарядные и пусковые устройства',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Лобзики',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Многофункциональный инструмент',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Перфораторы',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Пилы дисковые, ленточный, сабельные',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Рубанки и рейсмусы',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Углошлифмашины и полировальные машины',
          'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Шлифмашины и граверы',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Биты, насадки',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Буры',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Диски, круги',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Зубила, штробники',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Кордщётки',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Коронки',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Круги полировочные и шлифовальные',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Листы, сетки шлифовальные',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Масла и смазки для инструмента',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Пилки, полотна, ножи',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для бензопил',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для компрессоров',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для минимоек',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для пылесосов',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для сварки',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для степлеров',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Свёрла, патроны',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Фрезы',
          'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Шарошки',
          'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Гвоздодёры, ломы',
          'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Заклёпочники',
          'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Зубила, кернеры, штробники',
          'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Ключи разводные'
          ]
pack_in_cat = 100

In [8]:
df_res = pd.DataFrame()

for topic in tqdm(topics):
    df_topic = data[data['Категория'] == topic][:pack_in_cat]
    df_res = df_res.append(df_topic)

  0%|          | 0/127 [00:00<?, ?it/s]

In [9]:
df_res.shape

(5820, 5)


# Предобработка

In [10]:
import string
def remove_punctuation(text):
    return "".join([ch if ch not in string.punctuation else ' ' for ch in text])

def remove_numbers(text):
    return ''.join([i if not i.isdigit() else ' ' for i in text])

import re
def remove_multiple_spaces(text):
	return re.sub(r'\s+', ' ', text, flags=re.I)

import nltk
nltk.download('stopwords')
from nltk.stem import *
from nltk.corpus import stopwords
from pymystem3 import Mystem
from string import punctuation
mystem = Mystem() 

russian_stopwords = stopwords.words("russian")
russian_stopwords.extend(['…', '«', '»', '...'])
def lemmatize_text(text):
    tokens = mystem.lemmatize(text.lower())
    tokens = [token for token in tokens if token not in russian_stopwords and token != " "]
    text = " ".join(tokens)
    return text

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/mugichu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [11]:
prep_text = [remove_multiple_spaces(remove_numbers(remove_punctuation(text.lower()))) for text in tqdm(df_res['Название'])]

  0%|          | 0/5820 [00:00<?, ?it/s]

In [12]:
len(prep_text)
prep_text[0]

'проходка borge кровельная d мм прямая № '

In [13]:
df_res['text_prep'] = prep_text
df_res.head(1)

,Название,Артикул,Категория,Цена без карты,Цена с картой,text_prep
0,Проходка BORGE Кровельная D6-50мм прямая №1,17162301,"Главная,Каталог,Строительные материалы,Кровля,...",329.33 ₽,312.86 ₽,проходка borge кровельная d мм прямая №

In [14]:
from nltk.stem.snowball import SnowballStemmer 
stemmer = SnowballStemmer("russian")

In [15]:
russian_stopwords = stopwords.words("russian")
russian_stopwords.extend(['…', '«', '»', '...', 'т.д.', 'т', 'д','Главная','Каталог'])

In [16]:
import nltk
nltk.download('punkt')
from nltk import word_tokenize
text = df_res['text_prep'][0]
word_tokenize(text)

[nltk_data] Downloading package punkt to /home/mugichu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

['проходка', 'borge', 'кровельная', 'd', 'мм', 'прямая', '№']

In [17]:
from nltk import word_tokenize

stemmed_texts_list = []
for text in tqdm(df_res['text_prep']):
    tokens = word_tokenize(text)    
    stemmed_tokens = [stemmer.stem(token) for token in tokens if token not in russian_stopwords]
    text = " ".join(stemmed_tokens)
    stemmed_texts_list.append(text)

df_res['text_stem'] = stemmed_texts_list

  0%|          | 0/5820 [00:00<?, ?it/s]

In [18]:
def remove_stop_words(text):
    tokens = word_tokenize(text) 
    tokens = [token for token in tokens if token not in russian_stopwords and token != ' ']
    return " ".join(tokens)

In [19]:
from nltk import word_tokenize

sw_texts_list = []
for text in tqdm(df_res['text_prep']):
    tokens = word_tokenize(text)    
    tokens = [token for token in tokens if token not in russian_stopwords and token != ' ']
    text = " ".join(tokens)
    sw_texts_list.append(text)

df_res['text_sw'] = sw_texts_list

  0%|          | 0/5820 [00:00<?, ?it/s]

In [20]:
df_res['text_sw'][0]

'проходка borge кровельная d мм прямая №'

In [21]:
df_res.to_csv('sp_stemmed.csv')

In [22]:
df_res['text_stem'][0]

'проходк borge кровельн d мм прям №'

# Лемматизация

In [23]:
lemm_texts_list = []
for text in tqdm(df_res['text_sw']):
    #print(text)
    try:
        text_lem = mystem.lemmatize(text)
        tokens = [token for token in text_lem if token != ' ' and token not in russian_stopwords]
        text = " ".join(tokens)
        lemm_texts_list.append(text)
    except Exception as e:
        print(e)
    
df_res['text_lemm'] = lemm_texts_list

  0%|          | 0/5820 [00:00<?, ?it/s]

In [24]:
def lemmatize_text(text):
    text_lem = mystem.lemmatize(text)
    tokens = [token for token in text_lem if token != ' ']
    return " ".join(tokens)

In [25]:
df_res.to_csv('lemm.csv')

In [26]:
df_res = pd.read_csv('lemm.csv', encoding = 'utf-8')

In [27]:
df_res.head()

,Unnamed: 0,Название,Артикул,Категория,Цена без карты,Цена с картой,text_prep,text_stem,text_sw,text_lemm
0,0,Проходка BORGE Кровельная D6-50мм прямая №1,17162301,"Главная,Каталог,Строительные материалы,Кровля,...",329.33 ₽,312.86 ₽,проходка borge кровельная d мм прямая №,проходк borge кровельн d мм прям №,проходка borge кровельная d мм прямая №,проходка borge кровельный d мм прямой № \n
1,1,Аэратор ТЕХНОНИКОЛЬ КТВ,17575401,"Главная,Каталог,Строительные материалы,Кровля,...",1 529.00 ₽,1 452.55 ₽,аэратор технониколь ктв,аэратор техноникол ктв,аэратор технониколь ктв,аэратор технониколь ктв \n
2,2,Аэратор ТЕХНОНИКОЛЬ Pilot скатный,17575301,"Главная,Каталог,Строительные материалы,Кровля,...",3 008.00 ₽,2 857.60 ₽,аэратор технониколь pilot скатный,аэратор техноникол pilot скатн,аэратор технониколь pilot скатный,аэратор технониколь pilot скатный \n
3,3,Проходной элемент ТЕХНОНИКОЛЬ Shinglas,17575701,"Главная,Каталог,Строительные материалы,Кровля,...",1 172.00 ₽,1 113.40 ₽,проходной элемент технониколь shinglas,проходн элемент техноникол shinglas,проходной элемент технониколь shinglas,проходной элемент технониколь shinglas \n
4,4,Вентиль ТЕХНОНИКОЛЬ Skat кровельный,17575501,"Главная,Каталог,Строительные материалы,Кровля,...",2 396.00 ₽,2 276.20 ₽,вентиль технониколь skat кровельный,вентил техноникол skat кровельн,вентиль технониколь skat кровельный,вентиль технониколь skat кровельный \n

In [32]:
df_res['text_lemm'][0]

'проходка borge кровельный d мм прямой № \n'

In [33]:
X = df_res['text_sw']
y = df_res['Категория']

In [34]:
type(df_res['text_lemm'][0])

str

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state = 123)

In [36]:
my_cat = df_res['Категория'].unique()
my_cat

array(['Главная,Каталог,Строительные материалы,Кровля,Вентиляция для кровли',
       'Главная,Каталог,Строительные материалы,Кровля,Волнистый лист (ондулин)',
       'Главная,Каталог,Строительные материалы,Кровля,Кровельные мастики',
       'Главная,Каталог,Строительные материалы,Кровля,Кровельные ограждения, снегодержатели',
       'Главная,Каталог,Строительные материалы,Кровля,Металлочерепица',
       'Главная,Каталог,Строительные материалы,Кровля,Мягкая черепица',
       'Главная,Каталог,Строительные материалы,Кровля,Профнастил',
       'Главная,Каталог,Строительные материалы,Кровля,Рулонная кровля',
       'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Затирки',
       'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Клеи',
       'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Ровнители для пола',
       'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Специальные смеси',
       'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Шпаклевки',
       'Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Штукатурки',
       'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Гипсокартон',
       'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Комплектующие для гипсокартона',
       'Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Профиль для гипсокартона',
       'Главная,Каталог,Строительные материалы,Материалы для кладки,Кирпич',
       'Главная,Каталог,Строительные материалы,Материалы для кладки,Пазогребневые блоки и плиты',
       'Главная,Каталог,Строительные материалы,Материалы для кладки,Пенобетонные блоки',
       'Главная,Каталог,Строительные материалы,Металлическая арматура',
       'Главная,Каталог,Строительные материалы,Столярные изделия,Вагонка,  блок-хаус',
       'Главная,Каталог,Строительные материалы,Столярные изделия,Двери жалюзийные',
       'Главная,Каталог,Строительные материалы,Столярные изделия,Деревянные окна',
       'Главная,Каталог,Строительные материалы,Столярные изделия,Доска для пола и комплектующие',
       'Главная,Каталог,Строительные материалы,Столярные изделия,Доска обрезная',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Специальный крепеж',
       'Главная,Каталог,Строительные материалы,Столярные изделия,Лестничные группы',
       'Главная,Каталог,Строительные материалы,Столярные изделия,Погонажные изделия',
       'Главная,Каталог,Строительные материалы,Листовые материалы,OSB',
       'Главная,Каталог,Строительные материалы,Листовые материалы,ДВП',
       'Главная,Каталог,Строительные материалы,Листовые материалы,ДСП',
       'Главная,Каталог,Строительные материалы,Листовые материалы,Металлические листы',
       'Главная,Каталог,Строительные материалы,Листовые материалы,Пластик',
       'Главная,Каталог,Строительные материалы,Листовые материалы,Фанера',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Гидроизоляционные материалы',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Лента изоляционная и соединительная',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Материалы для осушения и защиты от солей кладок старых зданий',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Минеральная теплоизоляция',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенопласт',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенополистирол',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Плёнки и утеплители',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Поролон и войлок',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Рулонные и битумные кровельные материалы',
       'Главная,Каталог,Строительные материалы,Материалы для изоляции,Уплотнители',
       'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Бордюры тротуарные и водостоки',
       'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Водостоки и дренаж',
       'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Кольца и колодцы',
       'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Плитка тротуарная и формы',
       'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Решетки водоприемные',
       'Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Трубы канализационные',
       'Главная,Каталог,Строительные материалы,Материалы для фасадов,Калитки и ограждения',
       'Главная,Каталог,Строительные материалы,Материалы для фасадов,Кованные изделия',
       'Главная,Каталог,Строительные материалы,Материалы для фасадов,Листовая кровля',
       'Главная,Каталог,Строительные материалы,Материалы для фасадов,Сайдинг',
       'Главная,Каталог,Строительные материалы,Материалы для фасадов,Система водоотвода',
       'Главная,Каталог,Двери, окна, замки,Двери межкомнатные',
       'Главная,Каталог,Двери, окна, замки,Двери стальные',
       'Главная,Каталог,Двери, окна, замки,Дверные коробки, наличники и доборы',
       'Главная,Каталог,Двери, окна, замки,Дверные доводчики',
       'Главная,Каталог,Двери, окна, замки,Ручки дверные',
       'Главная,Каталог,Двери, окна, замки,Стопоры дверные',
       'Главная,Каталог,Двери, окна, замки,Петли',
       'Главная,Каталог,Двери, окна, замки,Капители и арки',
       'Главная,Каталог,Двери, окна, замки,Аксессуары для дверей',
       'Главная,Каталог,Двери, окна, замки,Оконная группа,Монтаж окон',
       'Главная,Каталог,Двери, окна, замки,Оконная группа,Москитные сетки и плёнки для окон',
       'Главная,Каталог,Двери, окна, замки,Оконная группа,Оконная фурнитура',
       'Главная,Каталог,Двери, окна, замки,Оконная группа,Откосы',
       'Главная,Каталог,Двери, окна, замки,Оконная группа,Отливы',
       'Главная,Каталог,Двери, окна, замки,Оконная группа,Пластиковые окна',
       'Главная,Каталог,Двери, окна, замки,Оконная группа,Подоконники',
       'Главная,Каталог,Двери, окна, замки,Оконная группа,Уплотнители',
       'Главная,Каталог,Двери, окна, замки,Замки и комплектующие',
       'Главная,Каталог,Двери, окна, замки,Крючки, шпингалеты и задвижки',
       'Главная,Каталог,Двери, окна, замки,Заготовки ключей и брелоки',
       'Главная,Каталог,Двери, окна, замки,Дверцы для кошек',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Анкера',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Верёвки, шнуры',
       'Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Комплектующие для транспортировки грузов',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Гвозди',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Дюбели',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Заклёпки',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Крепления для зеркал',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Метрический крепеж, шайбы',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Навесные замки и комплектующие',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Пластины крепежные',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Саморезы',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Такелажный крепёж',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Уголки',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Хомуты, скобы',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Цепи и тросы',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы',
       'Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы кровельные',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Аккумуляторные дрели и шуруповерты',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Дрели',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Зарядные и пусковые устройства',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Лобзики',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Многофункциональный инструмент',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Перфораторы',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Пилы дисковые, ленточный, сабельные',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Рубанки и рейсмусы',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Углошлифмашины и полировальные машины',
       'Главная,Каталог,Инструменты и крепёж,Электроинструмент,Шлифмашины и граверы',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Биты, насадки',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Буры',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Диски, круги',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Зубила, штробники',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Кордщётки',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Коронки',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Круги полировочные и шлифовальные',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Листы, сетки шлифовальные',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Масла и смазки для инструмента',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Пилки, полотна, ножи',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для бензопил',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для компрессоров',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для минимоек',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для пылесосов',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для сварки',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для степлеров',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Свёрла, патроны',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Фрезы',
       'Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Шарошки',
       'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Гвоздодёры, ломы',
       'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Заклёпочники',
       'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Зубила, кернеры, штробники',
       'Главная,Каталог,Инструменты и крепёж,Столярно-слесарный инструмент,Ключи разводные'],
      dtype=object)

In [37]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
nb = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', MultinomialNB()),
              ])

In [39]:
%%time
nb.fit(X_train, y_train)

CPU times: user 41 ms, sys: 3.84 ms, total: 44.8 ms
Wall time: 46.6 ms

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

In [40]:
%%time
from sklearn.metrics import classification_report
y_pred = nb.predict(X_test)

CPU times: user 44.3 ms, sys: 4.28 ms, total: 48.6 ms
Wall time: 47.8 ms

In [41]:
X_test.iloc[0]

'шуруп кольцо стройбат х шт'

In [42]:
print(X_test.iloc[0], y_test.iloc[0], y_pred[0])

шуруп кольцо стройбат х шт Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы

In [43]:
from sklearn.linear_model import SGDClassifier

sgd = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=127, max_iter=5, tol=None)),
               ])

In [44]:
%%time
sgd.fit(X_train, y_train)

CPU times: user 113 ms, sys: 0 ns, total: 113 ms
Wall time: 113 ms

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf',
                 SGDClassifier(alpha=0.001, max_iter=5, random_state=127,
                               tol=None))])

In [45]:
%%time
y_pred = sgd.predict(X_test)

CPU times: user 29.1 ms, sys: 3.85 ms, total: 32.9 ms
Wall time: 31.8 ms

In [46]:
from sklearn.metrics import accuracy_score
print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred, target_names=my_cat))

accuracy 0.9116347569955817
                                                                                                                             precision    recall  f1-score   support

                                                        Главная,Каталог,Строительные материалы,Кровля,Вентиляция для кровли       0.94      0.82      0.88        39
                                                     Главная,Каталог,Строительные материалы,Кровля,Волнистый лист (ондулин)       0.99      1.00      0.99        69
                                                           Главная,Каталог,Строительные материалы,Кровля,Кровельные мастики       0.99      1.00      0.99        67
                                        Главная,Каталог,Строительные материалы,Кровля,Кровельные ограждения, снегодержатели       0.91      0.67      0.77        15
                                                              Главная,Каталог,Строительные материалы,Кровля,Металлочерепица       0.75      1.00      0.86        60
                                                              Главная,Каталог,Строительные материалы,Кровля,Мягкая черепица       1.00      1.00      1.00         3
                                                                   Главная,Каталог,Строительные материалы,Кровля,Профнастил       0.98      0.98      0.98        82
                                                              Главная,Каталог,Строительные материалы,Кровля,Рулонная кровля       0.88      0.87      0.87        68
                                             Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Затирки       1.00      0.87      0.93        15
                                                Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Клеи       0.82      1.00      0.90        45
                                  Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Ровнители для пола       1.00      0.52      0.69        21
                                   Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Специальные смеси       0.80      0.80      0.80         5
                                           Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Шпаклевки       0.76      0.50      0.60        26
                                          Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Штукатурки       1.00      1.00      1.00         6
                                                    Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Гипсокартон       1.00      1.00      1.00         8
                                 Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Комплектующие для гипсокартона       0.56      1.00      0.71         5
                                       Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Профиль для гипсокартона       0.92      1.00      0.96        22
                                                         Главная,Каталог,Строительные материалы,Материалы для кладки,Кирпич       1.00      0.60      0.75         5
                                    Главная,Каталог,Строительные материалы,Материалы для кладки,Пазогребневые блоки и плиты       0.96      1.00      0.98        55
                                             Главная,Каталог,Строительные материалы,Материалы для кладки,Пенобетонные блоки       0.84      1.00      0.91        75
                                                              Главная,Каталог,Строительные материалы,Металлическая арматура       1.00      0.95      0.97        39
                                               Главная,Каталог,Строительные материалы,Столярные изделия,Вагонка,  блок-хаус       0.95      1.00      0.98        59
                                                  Главная,Каталог,Строительные материалы,Столярные изделия,Двери жалюзийные       0.91      1.00      0.96        64
                                                   Главная,Каталог,Строительные материалы,Столярные изделия,Деревянные окна       0.99      1.00      0.99        72
                                    Главная,Каталог,Строительные материалы,Столярные изделия,Доска для пола и комплектующие       0.94      1.00      0.97        68
                                                    Главная,Каталог,Строительные материалы,Столярные изделия,Доска обрезная       1.00      1.00      1.00        39
                                          Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Специальный крепеж       0.95      1.00      0.98        21
                                                 Главная,Каталог,Строительные материалы,Столярные изделия,Лестничные группы       0.86      0.98      0.92        65
                                                Главная,Каталог,Строительные материалы,Столярные изделия,Погонажные изделия       0.96      0.93      0.94        55
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,OSB       0.97      0.97      0.97        33
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,ДВП       1.00      1.00      1.00        71
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,ДСП       1.00      0.88      0.94        58
                                              Главная,Каталог,Строительные материалы,Листовые материалы,Металлические листы       0.94      0.84      0.89        69
                                                          Главная,Каталог,Строительные материалы,Листовые материалы,Пластик       0.88      1.00      0.94        72
                                                           Главная,Каталог,Строительные материалы,Листовые материалы,Фанера       0.96      0.99      0.97        75
                                  Главная,Каталог,Строительные материалы,Материалы для изоляции,Гидроизоляционные материалы       0.85      1.00      0.92        40
                          Главная,Каталог,Строительные материалы,Материалы для изоляции,Лента изоляционная и соединительная       0.99      1.00      0.99        67
Главная,Каталог,Строительные материалы,Материалы для изоляции,Материалы для осушения и защиты от солей кладок старых зданий       0.97      1.00      0.98        59
                                    Главная,Каталог,Строительные материалы,Материалы для изоляции,Минеральная теплоизоляция       1.00      0.64      0.78        22
                                                    Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенопласт       0.75      0.90      0.82        72
                                               Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенополистирол       1.00      1.00      1.00        73
                                          Главная,Каталог,Строительные материалы,Материалы для изоляции,Плёнки и утеплители       1.00      0.79      0.88        75
                                             Главная,Каталог,Строительные материалы,Материалы для изоляции,Поролон и войлок       1.00      1.00      1.00        24
                     Главная,Каталог,Строительные материалы,Материалы для изоляции,Рулонные и битумные кровельные материалы       1.00      0.93      0.96        42
                                                  Главная,Каталог,Строительные материалы,Материалы для изоляции,Уплотнители       0.96      0.71      0.82        70
                  Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Бордюры тротуарные и водостоки       0.94      0.94      0.94        69
                              Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Водостоки и дренаж       0.82      0.93      0.87        71
                                Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Кольца и колодцы       1.00      0.94      0.97        17
                       Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Плитка тротуарная и формы       0.98      0.97      0.98        66
                            Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Решетки водоприемные       0.98      1.00      0.99        41
                           Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Трубы канализационные       0.57      1.00      0.73        16
                                          Главная,Каталог,Строительные материалы,Материалы для фасадов,Калитки и ограждения       0.81      0.93      0.87        14
                                              Главная,Каталог,Строительные материалы,Материалы для фасадов,Кованные изделия       0.97      0.89      0.93        35
                                               Главная,Каталог,Строительные материалы,Материалы для фасадов,Листовая кровля       1.00      0.88      0.94        42
                                                       Главная,Каталог,Строительные материалы,Материалы для фасадов,Сайдинг       1.00      0.88      0.94        17
                                            Главная,Каталог,Строительные материалы,Материалы для фасадов,Система водоотвода       1.00      0.92      0.96        72
                                                                      Главная,Каталог,Двери, окна, замки,Двери межкомнатные       0.92      0.97      0.94        67
                                                                          Главная,Каталог,Двери, окна, замки,Двери стальные       0.81      0.83      0.82        36
                                                     Главная,Каталог,Двери, окна, замки,Дверные коробки, наличники и доборы       1.00      1.00      1.00         4
                                                                       Главная,Каталог,Двери, окна, замки,Дверные доводчики       1.00      0.62      0.77         8
                                                                           Главная,Каталог,Двери, окна, замки,Ручки дверные       0.70      0.78      0.74        18
                                                                         Главная,Каталог,Двери, окна, замки,Стопоры дверные       0.58      1.00      0.74         7
                                                                                   Главная,Каталог,Двери, окна, замки,Петли       0.94      0.91      0.93        56
                                                                         Главная,Каталог,Двери, окна, замки,Капители и арки       1.00      0.76      0.86        21
                                                                   Главная,Каталог,Двери, окна, замки,Аксессуары для дверей       0.40      1.00      0.57         2
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Монтаж окон       1.00      0.94      0.97        17
                                        Главная,Каталог,Двери, окна, замки,Оконная группа,Москитные сетки и плёнки для окон       0.00      0.00      0.00         7
                                                        Главная,Каталог,Двери, окна, замки,Оконная группа,Оконная фурнитура       0.92      1.00      0.96        22
                                                                   Главная,Каталог,Двери, окна, замки,Оконная группа,Откосы       1.00      1.00      1.00        39
                                                                   Главная,Каталог,Двери, окна, замки,Оконная группа,Отливы       1.00      1.00      1.00         8
                                                         Главная,Каталог,Двери, окна, замки,Оконная группа,Пластиковые окна       0.83      1.00      0.91        30
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Подоконники       0.90      0.86      0.88        21
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Уплотнители       1.00      0.47      0.64        17
                                                                   Главная,Каталог,Двери, окна, замки,Замки и комплектующие       0.86      0.89      0.87        27
                                                           Главная,Каталог,Двери, окна, замки,Крючки, шпингалеты и задвижки       0.00      0.00      0.00         3
                                                              Главная,Каталог,Двери, окна, замки,Заготовки ключей и брелоки       0.86      0.92      0.89        13
                                                                        Главная,Каталог,Двери, окна, замки,Дверцы для кошек       0.86      0.80      0.83        15
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Анкера       0.94      0.96      0.95        80
                                              Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Верёвки, шнуры       1.00      0.70      0.82        23
              Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Комплектующие для транспортировки грузов       0.00      0.00      0.00         1
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Гвозди       1.00      1.00      1.00         3
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Дюбели       1.00      0.80      0.89         5
                                                    Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Заклёпки       0.86      1.00      0.93        19
                                        Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Крепления для зеркал       1.00      0.87      0.93        30
                                   Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Метрический крепеж, шайбы       1.00      0.80      0.89        25
                              Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Навесные замки и комплектующие       1.00      1.00      1.00         8
                                          Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Пластины крепежные       1.00      0.81      0.89        21
                                                    Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Саморезы       0.00      0.00      0.00         7
                                           Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Такелажный крепёж       0.25      1.00      0.40         1
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Уголки       1.00      0.76      0.86        25
                                               Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Хомуты, скобы       1.00      1.00      1.00         2
                                                Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Цепи и тросы       1.00      0.36      0.53        11
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы       0.70      0.98      0.81        56
                                           Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы кровельные       1.00      1.00      1.00         3
                                  Главная,Каталог,Инструменты и крепёж,Электроинструмент,Аккумуляторные дрели и шуруповерты       0.94      0.76      0.84        21
                                                               Главная,Каталог,Инструменты и крепёж,Электроинструмент,Дрели       0.96      1.00      0.98        22
                                      Главная,Каталог,Инструменты и крепёж,Электроинструмент,Зарядные и пусковые устройства       1.00      0.62      0.77         8
                                                             Главная,Каталог,Инструменты и крепёж,Электроинструмент,Лобзики       0.00      0.00      0.00         2
                                      Главная,Каталог,Инструменты и крепёж,Электроинструмент,Многофункциональный инструмент       0.00      0.00      0.00         1
                                                         Главная,Каталог,Инструменты и крепёж,Электроинструмент,Перфораторы       1.00      1.00      1.00         4
                                 Главная,Каталог,Инструменты и крепёж,Электроинструмент,Пилы дисковые, ленточный, сабельные       0.92      0.92      0.92        24
                                                  Главная,Каталог,Инструменты и крепёж,Электроинструмент,Рубанки и рейсмусы       0.64      0.78      0.70        18
                               Главная,Каталог,Инструменты и крепёж,Электроинструмент,Углошлифмашины и полировальные машины       0.86      1.00      0.92        18
                                                Главная,Каталог,Инструменты и крепёж,Электроинструмент,Шлифмашины и граверы       1.00      0.88      0.93         8
                                     Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Биты, насадки       1.00      1.00      1.00        36
                                              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Буры       0.00      0.00      0.00         9
                                      Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Диски, круги       0.98      1.00      0.99        40
                                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Зубила, штробники       0.00      0.00      0.00         1
                                         Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Кордщётки       0.80      0.97      0.88        66
                                           Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Коронки       0.92      0.97      0.95        72
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Круги полировочные и шлифовальные       0.86      0.84      0.85        76
                         Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Листы, сетки шлифовальные       1.00      0.56      0.71         9
                    Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Масла и смазки для инструмента       0.67      1.00      0.80         8
                              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Пилки, полотна, ножи       0.00      0.00      0.00         4
                  Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для бензопил       0.27      1.00      0.43         3
              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для компрессоров       0.00      0.00      0.00         5
                  Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для минимоек       0.92      0.88      0.90        41
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для пылесосов       0.97      0.97      0.97        71
                    Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для сварки       0.98      0.98      0.98        58
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для степлеров       0.96      1.00      0.98        22

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [47]:
from sklearn.linear_model import SGDClassifier

sgd = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42, max_iter=5, tol=None)),
               ])

In [48]:
%%time
sgd.fit(X_train, y_train)

CPU times: user 112 ms, sys: 0 ns, total: 112 ms
Wall time: 111 ms

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf',
                 SGDClassifier(alpha=0.001, max_iter=5, random_state=42,
                               tol=None))])

In [49]:
%%time
y_pred = sgd.predict(X_test)

CPU times: user 31.6 ms, sys: 176 µs, total: 31.7 ms
Wall time: 30.2 ms

In [50]:
print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred,target_names=my_cat))

accuracy 0.9094256259204713
                                                                                                                             precision    recall  f1-score   support

                                                        Главная,Каталог,Строительные материалы,Кровля,Вентиляция для кровли       0.94      0.82      0.88        39
                                                     Главная,Каталог,Строительные материалы,Кровля,Волнистый лист (ондулин)       0.99      1.00      0.99        69
                                                           Главная,Каталог,Строительные материалы,Кровля,Кровельные мастики       0.99      1.00      0.99        67
                                        Главная,Каталог,Строительные материалы,Кровля,Кровельные ограждения, снегодержатели       0.91      0.67      0.77        15
                                                              Главная,Каталог,Строительные материалы,Кровля,Металлочерепица       0.74      1.00      0.85        60
                                                              Главная,Каталог,Строительные материалы,Кровля,Мягкая черепица       1.00      1.00      1.00         3
                                                                   Главная,Каталог,Строительные материалы,Кровля,Профнастил       0.98      0.98      0.98        82
                                                              Главная,Каталог,Строительные материалы,Кровля,Рулонная кровля       0.88      0.87      0.87        68
                                             Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Затирки       1.00      0.87      0.93        15
                                                Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Клеи       0.88      1.00      0.94        45
                                  Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Ровнители для пола       1.00      0.57      0.73        21
                                   Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Специальные смеси       0.80      0.80      0.80         5
                                           Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Шпаклевки       0.87      0.50      0.63        26
                                          Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Штукатурки       1.00      1.00      1.00         6
                                                    Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Гипсокартон       1.00      1.00      1.00         8
                                 Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Комплектующие для гипсокартона       0.56      1.00      0.71         5
                                       Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Профиль для гипсокартона       0.92      1.00      0.96        22
                                                         Главная,Каталог,Строительные материалы,Материалы для кладки,Кирпич       1.00      0.60      0.75         5
                                    Главная,Каталог,Строительные материалы,Материалы для кладки,Пазогребневые блоки и плиты       0.96      1.00      0.98        55
                                             Главная,Каталог,Строительные материалы,Материалы для кладки,Пенобетонные блоки       0.84      1.00      0.91        75
                                                              Главная,Каталог,Строительные материалы,Металлическая арматура       0.93      0.95      0.94        39
                                               Главная,Каталог,Строительные материалы,Столярные изделия,Вагонка,  блок-хаус       0.95      1.00      0.98        59
                                                  Главная,Каталог,Строительные материалы,Столярные изделия,Двери жалюзийные       0.91      1.00      0.96        64
                                                   Главная,Каталог,Строительные материалы,Столярные изделия,Деревянные окна       0.99      1.00      0.99        72
                                    Главная,Каталог,Строительные материалы,Столярные изделия,Доска для пола и комплектующие       0.94      1.00      0.97        68
                                                    Главная,Каталог,Строительные материалы,Столярные изделия,Доска обрезная       1.00      1.00      1.00        39
                                          Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Специальный крепеж       0.95      1.00      0.98        21
                                                 Главная,Каталог,Строительные материалы,Столярные изделия,Лестничные группы       0.83      0.98      0.90        65
                                                Главная,Каталог,Строительные материалы,Столярные изделия,Погонажные изделия       0.96      0.93      0.94        55
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,OSB       0.82      0.97      0.89        33
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,ДВП       1.00      1.00      1.00        71
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,ДСП       1.00      0.88      0.94        58
                                              Главная,Каталог,Строительные материалы,Листовые материалы,Металлические листы       0.89      0.84      0.87        69
                                                          Главная,Каталог,Строительные материалы,Листовые материалы,Пластик       0.87      1.00      0.93        72
                                                           Главная,Каталог,Строительные материалы,Листовые материалы,Фанера       0.94      0.91      0.93        75
                                  Главная,Каталог,Строительные материалы,Материалы для изоляции,Гидроизоляционные материалы       0.85      1.00      0.92        40
                          Главная,Каталог,Строительные материалы,Материалы для изоляции,Лента изоляционная и соединительная       1.00      1.00      1.00        67
Главная,Каталог,Строительные материалы,Материалы для изоляции,Материалы для осушения и защиты от солей кладок старых зданий       0.98      1.00      0.99        59
                                    Главная,Каталог,Строительные материалы,Материалы для изоляции,Минеральная теплоизоляция       1.00      0.64      0.78        22
                                                    Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенопласт       0.72      0.89      0.80        72
                                               Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенополистирол       1.00      1.00      1.00        73
                                          Главная,Каталог,Строительные материалы,Материалы для изоляции,Плёнки и утеплители       1.00      0.79      0.88        75
                                             Главная,Каталог,Строительные материалы,Материалы для изоляции,Поролон и войлок       1.00      1.00      1.00        24
                     Главная,Каталог,Строительные материалы,Материалы для изоляции,Рулонные и битумные кровельные материалы       1.00      0.93      0.96        42
                                                  Главная,Каталог,Строительные материалы,Материалы для изоляции,Уплотнители       0.98      0.71      0.83        70
                  Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Бордюры тротуарные и водостоки       0.94      0.94      0.94        69
                              Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Водостоки и дренаж       0.81      0.90      0.85        71
                                Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Кольца и колодцы       1.00      0.94      0.97        17
                       Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Плитка тротуарная и формы       0.98      0.97      0.98        66
                            Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Решетки водоприемные       0.98      1.00      0.99        41
                           Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Трубы канализационные       0.55      1.00      0.71        16
                                          Главная,Каталог,Строительные материалы,Материалы для фасадов,Калитки и ограждения       0.68      0.93      0.79        14
                                              Главная,Каталог,Строительные материалы,Материалы для фасадов,Кованные изделия       0.97      0.89      0.93        35
                                               Главная,Каталог,Строительные материалы,Материалы для фасадов,Листовая кровля       1.00      0.88      0.94        42
                                                       Главная,Каталог,Строительные материалы,Материалы для фасадов,Сайдинг       1.00      0.88      0.94        17
                                            Главная,Каталог,Строительные материалы,Материалы для фасадов,Система водоотвода       0.97      0.92      0.94        72
                                                                      Главная,Каталог,Двери, окна, замки,Двери межкомнатные       0.92      0.97      0.94        67
                                                                          Главная,Каталог,Двери, окна, замки,Двери стальные       0.81      0.83      0.82        36
                                                     Главная,Каталог,Двери, окна, замки,Дверные коробки, наличники и доборы       1.00      1.00      1.00         4
                                                                       Главная,Каталог,Двери, окна, замки,Дверные доводчики       1.00      0.62      0.77         8
                                                                           Главная,Каталог,Двери, окна, замки,Ручки дверные       0.88      0.78      0.82        18
                                                                         Главная,Каталог,Двери, окна, замки,Стопоры дверные       0.58      1.00      0.74         7
                                                                                   Главная,Каталог,Двери, окна, замки,Петли       0.94      0.91      0.93        56
                                                                         Главная,Каталог,Двери, окна, замки,Капители и арки       0.94      0.76      0.84        21
                                                                   Главная,Каталог,Двери, окна, замки,Аксессуары для дверей       0.40      1.00      0.57         2
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Монтаж окон       1.00      0.94      0.97        17
                                        Главная,Каталог,Двери, окна, замки,Оконная группа,Москитные сетки и плёнки для окон       0.00      0.00      0.00         7
                                                        Главная,Каталог,Двери, окна, замки,Оконная группа,Оконная фурнитура       0.92      1.00      0.96        22
                                                                   Главная,Каталог,Двери, окна, замки,Оконная группа,Откосы       1.00      1.00      1.00        39
                                                                   Главная,Каталог,Двери, окна, замки,Оконная группа,Отливы       1.00      1.00      1.00         8
                                                         Главная,Каталог,Двери, окна, замки,Оконная группа,Пластиковые окна       0.88      1.00      0.94        30
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Подоконники       0.90      0.86      0.88        21
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Уплотнители       1.00      0.47      0.64        17
                                                                   Главная,Каталог,Двери, окна, замки,Замки и комплектующие       0.89      0.89      0.89        27
                                                           Главная,Каталог,Двери, окна, замки,Крючки, шпингалеты и задвижки       0.00      0.00      0.00         3
                                                              Главная,Каталог,Двери, окна, замки,Заготовки ключей и брелоки       0.87      1.00      0.93        13
                                                                        Главная,Каталог,Двери, окна, замки,Дверцы для кошек       0.92      0.80      0.86        15
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Анкера       0.94      0.96      0.95        80
                                              Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Верёвки, шнуры       1.00      0.70      0.82        23
              Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Комплектующие для транспортировки грузов       0.00      0.00      0.00         1
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Гвозди       1.00      1.00      1.00         3
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Дюбели       1.00      0.80      0.89         5
                                                    Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Заклёпки       0.86      1.00      0.93        19
                                        Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Крепления для зеркал       1.00      0.87      0.93        30
                                   Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Метрический крепеж, шайбы       1.00      0.84      0.91        25
                              Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Навесные замки и комплектующие       1.00      1.00      1.00         8
                                          Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Пластины крепежные       1.00      0.81      0.89        21
                                                    Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Саморезы       0.00      0.00      0.00         7
                                           Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Такелажный крепёж       0.25      1.00      0.40         1
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Уголки       1.00      0.64      0.78        25
                                               Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Хомуты, скобы       1.00      1.00      1.00         2
                                                Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Цепи и тросы       1.00      0.36      0.53        11
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы       0.68      0.98      0.80        56
                                           Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы кровельные       1.00      1.00      1.00         3
                                  Главная,Каталог,Инструменты и крепёж,Электроинструмент,Аккумуляторные дрели и шуруповерты       0.94      0.76      0.84        21
                                                               Главная,Каталог,Инструменты и крепёж,Электроинструмент,Дрели       0.96      1.00      0.98        22
                                      Главная,Каталог,Инструменты и крепёж,Электроинструмент,Зарядные и пусковые устройства       1.00      0.75      0.86         8
                                                             Главная,Каталог,Инструменты и крепёж,Электроинструмент,Лобзики       0.00      0.00      0.00         2
                                      Главная,Каталог,Инструменты и крепёж,Электроинструмент,Многофункциональный инструмент       0.00      0.00      0.00         1
                                                         Главная,Каталог,Инструменты и крепёж,Электроинструмент,Перфораторы       1.00      1.00      1.00         4
                                 Главная,Каталог,Инструменты и крепёж,Электроинструмент,Пилы дисковые, ленточный, сабельные       0.92      0.92      0.92        24
                                                  Главная,Каталог,Инструменты и крепёж,Электроинструмент,Рубанки и рейсмусы       0.64      0.78      0.70        18
                               Главная,Каталог,Инструменты и крепёж,Электроинструмент,Углошлифмашины и полировальные машины       0.86      1.00      0.92        18
                                                Главная,Каталог,Инструменты и крепёж,Электроинструмент,Шлифмашины и граверы       1.00      0.88      0.93         8
                                     Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Биты, насадки       1.00      1.00      1.00        36
                                              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Буры       0.00      0.00      0.00         9
                                      Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Диски, круги       0.98      1.00      0.99        40
                                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Зубила, штробники       0.00      0.00      0.00         1
                                         Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Кордщётки       0.81      0.97      0.88        66
                                           Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Коронки       0.93      0.96      0.95        72
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Круги полировочные и шлифовальные       0.86      0.84      0.85        76
                         Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Листы, сетки шлифовальные       1.00      0.56      0.71         9
                    Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Масла и смазки для инструмента       0.67      1.00      0.80         8
                              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Пилки, полотна, ножи       0.00      0.00      0.00         4
                  Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для бензопил       0.30      1.00      0.46         3
              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для компрессоров       0.00      0.00      0.00         5
                  Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для минимоек       0.92      0.88      0.90        41
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для пылесосов       0.97      0.97      0.97        71
                    Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для сварки       0.98      0.98      0.98        58
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для степлеров       0.96      1.00      0.98        22

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [51]:
from sklearn.linear_model import LogisticRegression

logreg = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', LogisticRegression(n_jobs=1, C=1e5)),
               ])

In [52]:
%%time
logreg.fit(X_train, y_train)

CPU times: user 3.32 s, sys: 15.6 ms, total: 3.34 s
Wall time: 3.34 s

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', LogisticRegression(C=100000.0, n_jobs=1))])

In [53]:
%%time
y_pred = logreg.predict(X_test)

CPU times: user 36.4 ms, sys: 0 ns, total: 36.4 ms
Wall time: 34.9 ms

In [54]:
print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred,target_names=my_cat))

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

accuracy 0.9148257241040746
                                                                                                                             precision    recall  f1-score   support

                                                        Главная,Каталог,Строительные материалы,Кровля,Вентиляция для кровли       0.89      0.85      0.87        39
                                                     Главная,Каталог,Строительные материалы,Кровля,Волнистый лист (ондулин)       0.99      1.00      0.99        69
                                                           Главная,Каталог,Строительные материалы,Кровля,Кровельные мастики       0.99      1.00      0.99        67
                                        Главная,Каталог,Строительные материалы,Кровля,Кровельные ограждения, снегодержатели       1.00      0.67      0.80        15
                                                              Главная,Каталог,Строительные материалы,Кровля,Металлочерепица       0.88      1.00      0.94        60
                                                              Главная,Каталог,Строительные материалы,Кровля,Мягкая черепица       1.00      1.00      1.00         3
                                                                   Главная,Каталог,Строительные материалы,Кровля,Профнастил       0.98      0.98      0.98        82
                                                              Главная,Каталог,Строительные материалы,Кровля,Рулонная кровля       0.92      0.87      0.89        68
                                             Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Затирки       1.00      0.87      0.93        15
                                                Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Клеи       0.83      1.00      0.91        45
                                  Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Ровнители для пола       1.00      0.57      0.73        21
                                   Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Специальные смеси       1.00      0.80      0.89         5
                                           Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Шпаклевки       0.58      0.73      0.64        26
                                          Главная,Каталог,Строительные материалы,Строительные сухие смеси и клеи,Штукатурки       1.00      1.00      1.00         6
                                                    Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Гипсокартон       1.00      1.00      1.00         8
                                 Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Комплектующие для гипсокартона       0.56      1.00      0.71         5
                                       Главная,Каталог,Строительные материалы,Строительство из ГКЛ,Профиль для гипсокартона       0.91      0.95      0.93        22
                                                         Главная,Каталог,Строительные материалы,Материалы для кладки,Кирпич       0.80      0.80      0.80         5
                                    Главная,Каталог,Строительные материалы,Материалы для кладки,Пазогребневые блоки и плиты       0.98      1.00      0.99        55
                                             Главная,Каталог,Строительные материалы,Материалы для кладки,Пенобетонные блоки       0.89      1.00      0.94        75
                                                              Главная,Каталог,Строительные материалы,Металлическая арматура       1.00      0.95      0.97        39
                                               Главная,Каталог,Строительные материалы,Столярные изделия,Вагонка,  блок-хаус       0.97      1.00      0.98        59
                                                  Главная,Каталог,Строительные материалы,Столярные изделия,Двери жалюзийные       0.90      0.98      0.94        64
                                                   Главная,Каталог,Строительные материалы,Столярные изделия,Деревянные окна       0.99      1.00      0.99        72
                                    Главная,Каталог,Строительные материалы,Столярные изделия,Доска для пола и комплектующие       0.82      1.00      0.90        68
                                                    Главная,Каталог,Строительные материалы,Столярные изделия,Доска обрезная       1.00      1.00      1.00        39
                                          Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Специальный крепеж       1.00      1.00      1.00        21
                                                 Главная,Каталог,Строительные материалы,Столярные изделия,Лестничные группы       0.86      0.98      0.92        65
                                                Главная,Каталог,Строительные материалы,Столярные изделия,Погонажные изделия       0.98      0.93      0.95        55
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,OSB       1.00      0.97      0.98        33
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,ДВП       1.00      1.00      1.00        71
                                                              Главная,Каталог,Строительные материалы,Листовые материалы,ДСП       1.00      0.88      0.94        58
                                              Главная,Каталог,Строительные материалы,Листовые материалы,Металлические листы       0.91      0.84      0.87        69
                                                          Главная,Каталог,Строительные материалы,Листовые материалы,Пластик       0.86      1.00      0.92        72
                                                           Главная,Каталог,Строительные материалы,Листовые материалы,Фанера       0.97      0.97      0.97        75
                                  Главная,Каталог,Строительные материалы,Материалы для изоляции,Гидроизоляционные материалы       0.93      1.00      0.96        40
                          Главная,Каталог,Строительные материалы,Материалы для изоляции,Лента изоляционная и соединительная       0.99      1.00      0.99        67
Главная,Каталог,Строительные материалы,Материалы для изоляции,Материалы для осушения и защиты от солей кладок старых зданий       1.00      1.00      1.00        59
                                    Главная,Каталог,Строительные материалы,Материалы для изоляции,Минеральная теплоизоляция       1.00      0.64      0.78        22
                                                    Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенопласт       0.82      0.90      0.86        72
                                               Главная,Каталог,Строительные материалы,Материалы для изоляции,Пенополистирол       0.92      1.00      0.96        73
                                          Главная,Каталог,Строительные материалы,Материалы для изоляции,Плёнки и утеплители       1.00      0.79      0.88        75
                                             Главная,Каталог,Строительные материалы,Материалы для изоляции,Поролон и войлок       1.00      1.00      1.00        24
                     Главная,Каталог,Строительные материалы,Материалы для изоляции,Рулонные и битумные кровельные материалы       1.00      0.93      0.96        42
                                                  Главная,Каталог,Строительные материалы,Материалы для изоляции,Уплотнители       0.84      0.77      0.81        70
                  Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Бордюры тротуарные и водостоки       0.92      0.86      0.89        69
                              Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Водостоки и дренаж       0.76      0.96      0.84        71
                                Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Кольца и колодцы       1.00      0.88      0.94        17
                       Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Плитка тротуарная и формы       1.00      0.95      0.98        66
                            Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Решетки водоприемные       0.98      1.00      0.99        41
                           Главная,Каталог,Строительные материалы,Материалы для тротуара и ограждение,Трубы канализационные       0.68      0.94      0.79        16
                                          Главная,Каталог,Строительные материалы,Материалы для фасадов,Калитки и ограждения       0.76      0.93      0.84        14
                                              Главная,Каталог,Строительные материалы,Материалы для фасадов,Кованные изделия       0.91      0.83      0.87        35
                                               Главная,Каталог,Строительные материалы,Материалы для фасадов,Листовая кровля       0.95      0.88      0.91        42
                                                       Главная,Каталог,Строительные материалы,Материалы для фасадов,Сайдинг       1.00      1.00      1.00        17
                                            Главная,Каталог,Строительные материалы,Материалы для фасадов,Система водоотвода       0.88      0.94      0.91        72
                                                                      Главная,Каталог,Двери, окна, замки,Двери межкомнатные       0.96      0.97      0.96        67
                                                                          Главная,Каталог,Двери, окна, замки,Двери стальные       0.94      0.83      0.88        36
                                                     Главная,Каталог,Двери, окна, замки,Дверные коробки, наличники и доборы       1.00      0.75      0.86         4
                                                                       Главная,Каталог,Двери, окна, замки,Дверные доводчики       1.00      0.62      0.77         8
                                                                           Главная,Каталог,Двери, окна, замки,Ручки дверные       0.88      0.78      0.82        18
                                                                         Главная,Каталог,Двери, окна, замки,Стопоры дверные       1.00      1.00      1.00         7
                                                                                   Главная,Каталог,Двери, окна, замки,Петли       0.94      0.88      0.91        56
                                                                         Главная,Каталог,Двери, окна, замки,Капители и арки       0.94      0.81      0.87        21
                                                                   Главная,Каталог,Двери, окна, замки,Аксессуары для дверей       0.40      1.00      0.57         2
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Монтаж окон       1.00      0.94      0.97        17
                                        Главная,Каталог,Двери, окна, замки,Оконная группа,Москитные сетки и плёнки для окон       0.00      0.00      0.00         7
                                                        Главная,Каталог,Двери, окна, замки,Оконная группа,Оконная фурнитура       0.88      1.00      0.94        22
                                                                   Главная,Каталог,Двери, окна, замки,Оконная группа,Откосы       1.00      1.00      1.00        39
                                                                   Главная,Каталог,Двери, окна, замки,Оконная группа,Отливы       1.00      0.12      0.22         8
                                                         Главная,Каталог,Двери, окна, замки,Оконная группа,Пластиковые окна       0.77      1.00      0.87        30
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Подоконники       0.86      0.86      0.86        21
                                                              Главная,Каталог,Двери, окна, замки,Оконная группа,Уплотнители       1.00      0.47      0.64        17
                                                                   Главная,Каталог,Двери, окна, замки,Замки и комплектующие       0.87      0.96      0.91        27
                                                           Главная,Каталог,Двери, окна, замки,Крючки, шпингалеты и задвижки       0.00      0.00      0.00         3
                                                              Главная,Каталог,Двери, окна, замки,Заготовки ключей и брелоки       0.86      0.92      0.89        13
                                                                        Главная,Каталог,Двери, окна, замки,Дверцы для кошек       0.86      0.80      0.83        15
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Анкера       0.97      0.96      0.97        80
                                              Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Верёвки, шнуры       1.00      0.70      0.82        23
              Главная,Каталог,Инструменты и крепёж,Подъём и транспортировка грузов,Комплектующие для транспортировки грузов       0.00      0.00      0.00         1
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Гвозди       1.00      1.00      1.00         3
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Дюбели       1.00      0.60      0.75         5
                                                    Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Заклёпки       0.86      1.00      0.93        19
                                        Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Крепления для зеркал       0.86      1.00      0.92        30
                                   Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Метрический крепеж, шайбы       0.96      0.96      0.96        25
                              Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Навесные замки и комплектующие       1.00      1.00      1.00         8
                                          Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Пластины крепежные       0.95      0.86      0.90        21
                                                    Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Саморезы       0.00      0.00      0.00         7
                                           Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Такелажный крепёж       0.25      1.00      0.40         1
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Уголки       0.72      0.92      0.81        25
                                               Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Хомуты, скобы       1.00      1.00      1.00         2
                                                Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Цепи и тросы       1.00      0.36      0.53        11
                                                      Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы       0.95      0.96      0.96        56
                                           Главная,Каталог,Инструменты и крепёж,Крепёж и скобяные изделия,Шурупы кровельные       1.00      1.00      1.00         3
                                  Главная,Каталог,Инструменты и крепёж,Электроинструмент,Аккумуляторные дрели и шуруповерты       0.80      0.76      0.78        21
                                                               Главная,Каталог,Инструменты и крепёж,Электроинструмент,Дрели       0.96      1.00      0.98        22
                                      Главная,Каталог,Инструменты и крепёж,Электроинструмент,Зарядные и пусковые устройства       1.00      0.75      0.86         8
                                                             Главная,Каталог,Инструменты и крепёж,Электроинструмент,Лобзики       0.00      0.00      0.00         2
                                      Главная,Каталог,Инструменты и крепёж,Электроинструмент,Многофункциональный инструмент       0.00      0.00      0.00         1
                                                         Главная,Каталог,Инструменты и крепёж,Электроинструмент,Перфораторы       1.00      1.00      1.00         4
                                 Главная,Каталог,Инструменты и крепёж,Электроинструмент,Пилы дисковые, ленточный, сабельные       0.91      0.83      0.87        24
                                                  Главная,Каталог,Инструменты и крепёж,Электроинструмент,Рубанки и рейсмусы       1.00      0.78      0.88        18
                               Главная,Каталог,Инструменты и крепёж,Электроинструмент,Углошлифмашины и полировальные машины       0.95      1.00      0.97        18
                                                Главная,Каталог,Инструменты и крепёж,Электроинструмент,Шлифмашины и граверы       1.00      0.88      0.93         8
                                     Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Биты, насадки       0.88      1.00      0.94        36
                                              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Буры       0.00      0.00      0.00         9
                                      Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Диски, круги       0.98      1.00      0.99        40
                                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Зубила, штробники       0.00      0.00      0.00         1
                                         Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Кордщётки       0.84      1.00      0.91        66
                                           Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Коронки       0.97      1.00      0.99        72
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Круги полировочные и шлифовальные       0.93      0.84      0.88        76
                         Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Листы, сетки шлифовальные       1.00      0.44      0.62         9
                    Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Масла и смазки для инструмента       0.67      1.00      0.80         8
                              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Пилки, полотна, ножи       0.00      0.00      0.00         4
                  Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для бензопил       0.27      1.00      0.43         3
              Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для компрессоров       0.00      0.00      0.00         5
                  Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для минимоек       0.95      0.90      0.92        41
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для пылесосов       1.00      0.90      0.95        71
                    Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для сварки       1.00      0.98      0.99        58
                 Главная,Каталог,Инструменты и крепёж,Расходные материалы для инструмента,Расходные материалы для степлеров       0.79      1.00      0.88        22

In [80]:
test_text ='нож'

In [81]:
test_text = remove_multiple_spaces(remove_numbers(remove_punctuation(test_text.lower())))
test_text = remove_stop_words(test_text)

In [82]:
%%time
test_text = lemmatize_text(test_text)

CPU times: user 1.03 ms, sys: 46 µs, total: 1.08 ms
Wall time: 716 µs

In [83]:
test_text

'нож \n'

In [84]:
test_pred = logreg.predict([test_text])
test_pred

array(['Главная,Каталог,Строительные материалы,Материалы для изоляции,Минеральная теплоизоляция'],
      dtype=object)